version: '3'
services:
  db:
    container_name: django_db
    image: mysql:8
    restart: 'always'
    ports:
      - "13306:3306"
    environment:
      MYSQL_DATABASE: django
      MYSQL_HOST: db
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./mysql-confd:/etc/mysql/conf.d
      - ./db:/var/lib/mysql
  web:
    container_name: django_web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "18000:8000"
    volumes:
      - .:/app
      - /tmp/app/mysqld:/run/mysqld
    depends_on:
      - db